import React from 'react';

const PrivacyModal = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content royal-card" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose} aria-label="Close Modal">&times;</button>
        
        <div className="modal-header">
          <h2 className="modal-title">Privacy & Data Ethics</h2>
          <p className="modal-subtitle">Commitment to integrity, privacy, and cultural preservation.</p>
        </div>
        
        <div className="modal-body">
          <section className="modal-section">
            <h3 className="section-heading">Objective & Scholarly Nature</h3>
            <p>
              The <strong>All About Ramayana</strong> project is a non-profit digital research initiative designed to make the nuances of the Valmiki Ramayana accessible through advanced linguistic models. 
            </p>
          </section>

          <section className="modal-section">
            <h3 className="section-heading">Data & Cookie Policy</h3>
            <p>
              We operate on a principle of <strong>strict data minimization</strong>. We use cookies and similar technologies (including <strong>Google AdSense</strong>) to serve ads, analyze site traffic, and refine AI accuracy.
            </p>
            <ul className="policy-list">
              <li><strong>Advertising:</strong> Third-party vendors, including Google, use cookies to serve ads based on your prior visits to this or other websites.</li>
              <li><strong>Anonymization:</strong> We do not collect names, phone numbers, or physical addresses. All query logs are anonymized.</li>
              <li><strong>Opt-out:</strong> You may opt-out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" target="_blank">Google Ads Settings</a>.</li>
            </ul>
          </section>

          <section className="modal-section">
            <h3 className="section-heading">Terms of Service</h3>
            <p>
              By using this AI Guide, you agree that responses are generated by a Large Language Model and should be cross-referenced with primary Sanskrit sources for academic or theological certainty. We are not liable for interpretive variations.
            </p>
          </section>

          <section className="modal-section">
            <h3 className="section-heading">Contact Us</h3>
            <p>
              For scholarly inquiries, data removal requests, or reporting inaccuracies, please contact our administration:
            </p>
            <p className="contact-info">
              <strong>Email:</strong> <a href="mailto:devamgupta.business@gmail.com">devamgupta.business@gmail.com</a>
            </p>
          </section>

          <div className="modal-footer-professional">
            <p className="disclaimer-text">By continuing to use this platform, you acknowledge these terms of data conduct and our use of AdSense cookies.</p>
            <button className="btn-royal-solid" onClick={onClose}>Acknowledge & Close</button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyModal;
